import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

const seedPath = resolve(import.meta.dirname, "..", "seed_data", "recipes.json");
const recipes = JSON.parse(readFileSync(seedPath, "utf-8"));

const newRecipes = [
  // STAPLES
  {
    id: "seed-018",
    name: "Chicken Caesar Salad",
    complexity: "staple",
    description: "Grilled chicken over romaine with caesar dressing and croutons.",
    ingredients: [
      { name: "chicken breast", quantity: 2, unit: "pieces", category: "meat" },
      { name: "romaine lettuce", quantity: 2, unit: "heads", category: "produce" },
      { name: "caesar dressing", quantity: 0.5, unit: "cup", category: "condiments" },
      { name: "croutons", quantity: 1, unit: "cup", category: "bread" },
      { name: "parmesan cheese", quantity: 0.25, unit: "cup", category: "dairy" },
    ],
    steps: ["Grill chicken, slice. Chop romaine. Toss with dressing, croutons, and parmesan."],
    cookTime: 15, prepTime: 10, servings: 4,
    tags: ["salad", "chicken", "quick", "staple", "healthy"],
    categories: ["dinner", "lunch"],
  },
  {
    id: "seed-019",
    name: "Steak with Baked Potatoes",
    complexity: "staple",
    description: "Pan-seared or grilled steaks with loaded baked potatoes.",
    ingredients: [
      { name: "ribeye steak", quantity: 2, unit: "pieces", category: "meat" },
      { name: "russet potatoes", quantity: 4, unit: "large", category: "produce" },
      { name: "butter", quantity: 3, unit: "tbsp", category: "dairy" },
      { name: "sour cream", quantity: 0.5, unit: "cup", category: "dairy" },
      { name: "shredded cheddar cheese", quantity: 0.5, unit: "cup", category: "dairy" },
    ],
    steps: ["Bake potatoes at 400F for 1 hour. Season and cook steaks. Load potatoes with toppings."],
    cookTime: 60, prepTime: 5, servings: 4,
    tags: ["beef", "comfort-food", "staple"],
    categories: ["dinner"],
  },
  {
    id: "seed-020",
    name: "Grilled Sausages with Peppers",
    complexity: "staple",
    description: "Italian sausages with grilled peppers and onions on hoagie rolls.",
    ingredients: [
      { name: "Italian sausage links", quantity: 6, unit: "links", category: "meat" },
      { name: "bell peppers", quantity: 3, unit: "medium", category: "produce" },
      { name: "onion", quantity: 1, unit: "large", category: "produce" },
      { name: "hoagie rolls", quantity: 6, unit: "rolls", category: "bread" },
    ],
    steps: ["Grill sausages. Sauté sliced peppers and onions. Serve on rolls."],
    cookTime: 20, prepTime: 5, servings: 4,
    tags: ["italian", "quick", "staple", "grilling"],
    categories: ["dinner"],
  },
  {
    id: "seed-021",
    name: "Fish Tacos",
    complexity: "staple",
    description: "Seasoned white fish in tortillas with slaw and lime crema.",
    ingredients: [
      { name: "tilapia fillets", quantity: 1, unit: "lb", category: "seafood" },
      { name: "flour tortillas", quantity: 8, unit: "small", category: "bread" },
      { name: "coleslaw mix", quantity: 2, unit: "cups", category: "produce" },
      { name: "sour cream", quantity: 0.5, unit: "cup", category: "dairy" },
      { name: "lime", quantity: 2, unit: "whole", category: "produce" },
      { name: "chili powder", quantity: 1, unit: "tsp", category: "spices" },
    ],
    steps: ["Season fish with chili powder, pan-fry. Mix sour cream with lime. Assemble tacos with slaw."],
    cookTime: 10, prepTime: 10, servings: 4,
    tags: ["seafood", "mexican", "quick", "staple"],
    categories: ["dinner"],
  },
  {
    id: "seed-022",
    name: "BLT Sandwiches with Soup",
    complexity: "staple",
    description: "Classic bacon, lettuce, tomato sandwiches with a side of soup.",
    ingredients: [
      { name: "bacon", quantity: 12, unit: "slices", category: "meat" },
      { name: "bread", quantity: 8, unit: "slices", category: "bread" },
      { name: "lettuce", quantity: 4, unit: "leaves", category: "produce" },
      { name: "tomato", quantity: 2, unit: "large", category: "produce" },
      { name: "mayonnaise", quantity: 3, unit: "tbsp", category: "condiments" },
      { name: "canned tomato soup", quantity: 2, unit: "cans", category: "canned" },
    ],
    steps: ["Cook bacon. Toast bread. Assemble BLTs. Heat soup."],
    cookTime: 15, prepTime: 5, servings: 4,
    tags: ["american", "quick", "staple", "lunch"],
    categories: ["dinner", "lunch"],
  },
  // INVOLVED
  {
    id: "seed-023",
    name: "Beef Stroganoff",
    complexity: "involved",
    description: "Tender beef strips in a rich mushroom cream sauce over egg noodles.",
    ingredients: [
      { name: "beef sirloin", quantity: 1.5, unit: "lbs", category: "meat" },
      { name: "egg noodles", quantity: 12, unit: "oz", category: "pasta" },
      { name: "mushrooms", quantity: 8, unit: "oz", category: "produce" },
      { name: "onion", quantity: 1, unit: "medium", category: "produce" },
      { name: "garlic", quantity: 3, unit: "cloves", category: "produce" },
      { name: "beef broth", quantity: 1, unit: "cup", category: "canned" },
      { name: "sour cream", quantity: 0.75, unit: "cup", category: "dairy" },
      { name: "Worcestershire sauce", quantity: 2, unit: "tbsp", category: "condiments" },
      { name: "flour", quantity: 2, unit: "tbsp", category: "pantry" },
      { name: "butter", quantity: 3, unit: "tbsp", category: "dairy" },
      { name: "fresh parsley", quantity: 2, unit: "tbsp", category: "produce" },
    ],
    steps: [
      "Slice beef thinly. Season with salt and pepper.",
      "Cook egg noodles per package.",
      "Sear beef in batches in hot butter. Remove and set aside.",
      "Sauté mushrooms and onion until golden. Add garlic.",
      "Sprinkle flour, stir 1 minute. Add broth and Worcestershire. Simmer until thick.",
      "Remove from heat, stir in sour cream. Return beef.",
      "Serve over egg noodles with parsley.",
    ],
    cookTime: 30, prepTime: 20, servings: 4,
    tags: ["beef", "comfort-food", "creamy", "pasta"],
    categories: ["dinner"],
  },
  {
    id: "seed-024",
    name: "Thai Green Curry",
    complexity: "involved",
    description: "Coconut milk curry with vegetables and chicken. Aromatic and warming.",
    ingredients: [
      { name: "chicken thighs", quantity: 1.5, unit: "lbs", category: "meat" },
      { name: "green curry paste", quantity: 3, unit: "tbsp", category: "condiments" },
      { name: "coconut milk", quantity: 2, unit: "14-oz cans", category: "canned" },
      { name: "bamboo shoots", quantity: 8, unit: "oz", category: "canned" },
      { name: "bell pepper", quantity: 1, unit: "medium", category: "produce" },
      { name: "zucchini", quantity: 1, unit: "medium", category: "produce" },
      { name: "fish sauce", quantity: 2, unit: "tbsp", category: "condiments" },
      { name: "brown sugar", quantity: 1, unit: "tbsp", category: "pantry" },
      { name: "Thai basil", quantity: 0.5, unit: "cup", category: "produce" },
      { name: "jasmine rice", quantity: 2, unit: "cups", category: "pantry" },
      { name: "lime", quantity: 1, unit: "whole", category: "produce" },
    ],
    steps: [
      "Cut chicken into pieces. Slice veggies.",
      "Cook curry paste in oil 1 minute. Add coconut milk, simmer.",
      "Add chicken, cook 10 minutes. Add vegetables, cook 5 more.",
      "Season with fish sauce and sugar. Serve over rice with basil and lime.",
    ],
    cookTime: 25, prepTime: 15, servings: 4,
    tags: ["thai", "curry", "chicken", "asian"],
    categories: ["dinner"],
  },
  {
    id: "seed-025",
    name: "Homemade Pizza",
    complexity: "involved",
    description: "From-scratch pizza dough with your favorite toppings. Fun family project.",
    ingredients: [
      { name: "bread flour", quantity: 3.5, unit: "cups", category: "pantry" },
      { name: "active dry yeast", quantity: 1, unit: "packet", category: "pantry" },
      { name: "olive oil", quantity: 3, unit: "tbsp", category: "pantry" },
      { name: "pizza sauce", quantity: 1, unit: "cup", category: "canned" },
      { name: "mozzarella cheese", quantity: 3, unit: "cups", category: "dairy" },
      { name: "pepperoni", quantity: 4, unit: "oz", category: "meat" },
      { name: "bell pepper", quantity: 1, unit: "medium", category: "produce" },
      { name: "mushrooms", quantity: 4, unit: "oz", category: "produce" },
      { name: "Italian sausage", quantity: 0.5, unit: "lb", category: "meat" },
    ],
    steps: [
      "Dissolve yeast in warm water. Let sit 5 minutes.",
      "Mix flour and salt. Add yeast mixture and oil. Knead 8-10 minutes.",
      "Let rise 1 hour until doubled.",
      "Preheat oven to 475F. Brown sausage. Slice toppings.",
      "Roll dough, top with sauce, cheese, toppings. Bake 12-15 minutes.",
    ],
    cookTime: 15, prepTime: 90, servings: 6,
    tags: ["italian", "baking", "family-fun", "weekend"],
    categories: ["dinner"],
  },
  {
    id: "seed-026",
    name: "Chicken Parmesan",
    complexity: "involved",
    description: "Breaded chicken cutlets with marinara and melted mozzarella over spaghetti.",
    ingredients: [
      { name: "chicken breast", quantity: 4, unit: "pieces", category: "meat" },
      { name: "breadcrumbs", quantity: 1.5, unit: "cups", category: "pantry" },
      { name: "parmesan cheese", quantity: 0.75, unit: "cup", category: "dairy" },
      { name: "eggs", quantity: 2, unit: "large", category: "dairy" },
      { name: "flour", quantity: 0.5, unit: "cup", category: "pantry" },
      { name: "marinara sauce", quantity: 2, unit: "cups", category: "canned" },
      { name: "mozzarella cheese", quantity: 1.5, unit: "cups", category: "dairy" },
      { name: "spaghetti", quantity: 1, unit: "lb", category: "pasta" },
      { name: "fresh basil", quantity: 0.25, unit: "cup", category: "produce" },
      { name: "vegetable oil", quantity: 0.5, unit: "cup", category: "pantry" },
    ],
    steps: [
      "Pound chicken to even thickness.",
      "Set up breading: flour, eggs, breadcrumbs mixed with parmesan.",
      "Bread each piece. Fry 4-5 minutes per side until golden.",
      "Top with marinara and mozzarella. Broil 3-4 minutes.",
      "Cook spaghetti. Serve chicken over pasta with basil.",
    ],
    cookTime: 25, prepTime: 25, servings: 4,
    tags: ["italian", "chicken", "comfort-food", "fried"],
    categories: ["dinner"],
  },
  // MORE STANDARDS
  {
    id: "seed-027",
    name: "Teriyaki Chicken Bowl",
    complexity: "standard",
    description: "Sweet teriyaki chicken over rice with steamed broccoli.",
    ingredients: [
      { name: "chicken thighs", quantity: 1.5, unit: "lbs", category: "meat" },
      { name: "soy sauce", quantity: 0.25, unit: "cup", category: "condiments" },
      { name: "honey", quantity: 3, unit: "tbsp", category: "pantry" },
      { name: "rice vinegar", quantity: 1, unit: "tbsp", category: "condiments" },
      { name: "garlic", quantity: 3, unit: "cloves", category: "produce" },
      { name: "ginger", quantity: 1, unit: "tbsp", category: "produce" },
      { name: "cornstarch", quantity: 1, unit: "tbsp", category: "pantry" },
      { name: "rice", quantity: 2, unit: "cups", category: "pantry" },
      { name: "broccoli", quantity: 2, unit: "cups", category: "produce" },
      { name: "sesame seeds", quantity: 1, unit: "tbsp", category: "pantry" },
    ],
    steps: [
      "Mix soy sauce, honey, vinegar, garlic, ginger, and cornstarch.",
      "Cook chicken until browned. Add sauce, simmer until glossy.",
      "Steam broccoli. Serve over rice with sesame seeds.",
    ],
    cookTime: 20, prepTime: 10, servings: 4,
    tags: ["asian", "chicken", "bowl", "quick"],
    categories: ["dinner"],
  },
  {
    id: "seed-028",
    name: "Stuffed Bell Peppers",
    complexity: "standard",
    description: "Bell peppers filled with seasoned ground beef, rice, and cheese.",
    ingredients: [
      { name: "bell peppers", quantity: 6, unit: "large", category: "produce" },
      { name: "ground beef", quantity: 1, unit: "lb", category: "meat" },
      { name: "rice", quantity: 1, unit: "cup", category: "pantry" },
      { name: "diced tomatoes", quantity: 14, unit: "oz", category: "canned" },
      { name: "shredded cheddar cheese", quantity: 1.5, unit: "cups", category: "dairy" },
      { name: "onion", quantity: 1, unit: "small", category: "produce" },
      { name: "garlic", quantity: 2, unit: "cloves", category: "produce" },
      { name: "Italian seasoning", quantity: 1, unit: "tsp", category: "spices" },
    ],
    steps: [
      "Cook rice. Cut tops off peppers, blanch 5 minutes.",
      "Brown beef with onion and garlic. Mix with rice, tomatoes, seasoning.",
      "Stuff peppers, top with cheese. Bake 375F for 25-30 minutes.",
    ],
    cookTime: 35, prepTime: 20, servings: 6,
    tags: ["beef", "comfort-food", "baked"],
    categories: ["dinner"],
  },
  {
    id: "seed-029",
    name: "Lemon Garlic Shrimp Pasta",
    complexity: "standard",
    description: "Quick shrimp pasta with a bright lemon garlic butter sauce.",
    ingredients: [
      { name: "large shrimp", quantity: 1, unit: "lb", category: "seafood" },
      { name: "penne pasta", quantity: 0.75, unit: "lb", category: "pasta" },
      { name: "butter", quantity: 3, unit: "tbsp", category: "dairy" },
      { name: "garlic", quantity: 4, unit: "cloves", category: "produce" },
      { name: "lemon", quantity: 2, unit: "whole", category: "produce" },
      { name: "white wine", quantity: 0.25, unit: "cup", category: "pantry" },
      { name: "red pepper flakes", quantity: 0.25, unit: "tsp", category: "spices" },
      { name: "fresh parsley", quantity: 0.25, unit: "cup", category: "produce" },
      { name: "parmesan cheese", quantity: 0.25, unit: "cup", category: "dairy" },
    ],
    steps: [
      "Cook pasta. Reserve 1 cup pasta water.",
      "Sauté garlic and red pepper flakes in butter.",
      "Add shrimp, cook 2-3 minutes per side. Add wine and lemon juice.",
      "Toss with pasta, parsley, and parmesan.",
    ],
    cookTime: 15, prepTime: 10, servings: 4,
    tags: ["seafood", "pasta", "quick", "italian"],
    categories: ["dinner"],
  },
];

recipes.push(...newRecipes);
writeFileSync(seedPath, JSON.stringify(recipes, null, 2) + "\n");

const counts = { staple: 0, standard: 0, involved: 0 };
recipes.forEach((r: { complexity: string }) => counts[r.complexity as keyof typeof counts]++);
console.log(`Total: ${recipes.length} recipes`);
console.log("Breakdown:", JSON.stringify(counts));
