/**
 * Static lookup table for common grocery/pantry items.
 * Keyed by lowercased, trimmed name.
 * Falls back to Claude Haiku for items not in this map.
 */

export interface CategoryEntry {
  displayName: string;
  category: string;
}

const entries: Array<[string | string[], CategoryEntry]> = [
  // ── Produce ────────────────────────────────────────────
  [["garlic", "garlic cloves"], { displayName: "Garlic", category: "produce" }],
  [["onion", "onions", "yellow onion", "yellow onions"], { displayName: "Onion", category: "produce" }],
  [["red onion", "red onions"], { displayName: "Red Onion", category: "produce" }],
  [["white onion", "white onions"], { displayName: "White Onion", category: "produce" }],
  [["shallot", "shallots"], { displayName: "Shallot", category: "produce" }],
  [["green onion", "green onions", "scallion", "scallions"], { displayName: "Green Onion", category: "produce" }],
  [["potato", "potatoes", "russet potato", "russet potatoes"], { displayName: "Potato", category: "produce" }],
  [["sweet potato", "sweet potatoes"], { displayName: "Sweet Potato", category: "produce" }],
  [["carrot", "carrots"], { displayName: "Carrot", category: "produce" }],
  [["celery"], { displayName: "Celery", category: "produce" }],
  [["bell pepper", "bell peppers"], { displayName: "Bell Pepper", category: "produce" }],
  [["red bell pepper", "red bell peppers"], { displayName: "Red Bell Pepper", category: "produce" }],
  [["green bell pepper", "green bell peppers"], { displayName: "Green Bell Pepper", category: "produce" }],
  [["jalapeno", "jalapeño", "jalapenos", "jalapeños"], { displayName: "Jalapeño", category: "produce" }],
  [["serrano pepper", "serrano peppers", "serrano"], { displayName: "Serrano Pepper", category: "produce" }],
  [["poblano pepper", "poblano", "poblanos"], { displayName: "Poblano Pepper", category: "produce" }],
  [["habanero", "habaneros"], { displayName: "Habanero", category: "produce" }],
  [["tomato", "tomatoes"], { displayName: "Tomato", category: "produce" }],
  [["roma tomato", "roma tomatoes"], { displayName: "Roma Tomato", category: "produce" }],
  [["cherry tomato", "cherry tomatoes"], { displayName: "Cherry Tomato", category: "produce" }],
  [["grape tomato", "grape tomatoes"], { displayName: "Grape Tomato", category: "produce" }],
  [["cucumber", "cucumbers"], { displayName: "Cucumber", category: "produce" }],
  [["zucchini", "zucchinis"], { displayName: "Zucchini", category: "produce" }],
  [["squash", "yellow squash"], { displayName: "Yellow Squash", category: "produce" }],
  [["broccoli"], { displayName: "Broccoli", category: "produce" }],
  [["cauliflower"], { displayName: "Cauliflower", category: "produce" }],
  [["spinach", "baby spinach"], { displayName: "Spinach", category: "produce" }],
  [["kale"], { displayName: "Kale", category: "produce" }],
  [["lettuce", "romaine", "romaine lettuce"], { displayName: "Romaine Lettuce", category: "produce" }],
  [["iceberg lettuce"], { displayName: "Iceberg Lettuce", category: "produce" }],
  [["arugula"], { displayName: "Arugula", category: "produce" }],
  [["mixed greens", "spring mix"], { displayName: "Mixed Greens", category: "produce" }],
  [["cabbage", "green cabbage"], { displayName: "Cabbage", category: "produce" }],
  [["red cabbage"], { displayName: "Red Cabbage", category: "produce" }],
  [["mushroom", "mushrooms", "white mushrooms"], { displayName: "Mushroom", category: "produce" }],
  [["cremini mushroom", "cremini mushrooms", "baby bella mushrooms"], { displayName: "Cremini Mushroom", category: "produce" }],
  [["portobello mushroom", "portobello mushrooms"], { displayName: "Portobello Mushroom", category: "produce" }],
  [["corn", "corn on the cob"], { displayName: "Corn", category: "produce" }],
  [["asparagus"], { displayName: "Asparagus", category: "produce" }],
  [["green bean", "green beans"], { displayName: "Green Bean", category: "produce" }],
  [["snap pea", "snap peas", "sugar snap peas"], { displayName: "Snap Peas", category: "produce" }],
  [["avocado", "avocados"], { displayName: "Avocado", category: "produce" }],
  [["lemon", "lemons"], { displayName: "Lemon", category: "produce" }],
  [["lime", "limes"], { displayName: "Lime", category: "produce" }],
  [["orange", "oranges"], { displayName: "Orange", category: "produce" }],
  [["apple", "apples"], { displayName: "Apple", category: "produce" }],
  [["banana", "bananas"], { displayName: "Banana", category: "produce" }],
  [["strawberry", "strawberries"], { displayName: "Strawberry", category: "produce" }],
  [["blueberry", "blueberries"], { displayName: "Blueberry", category: "produce" }],
  [["raspberry", "raspberries"], { displayName: "Raspberry", category: "produce" }],
  [["grape", "grapes"], { displayName: "Grape", category: "produce" }],
  [["ginger", "fresh ginger", "ginger root"], { displayName: "Ginger", category: "produce" }],
  [["cilantro", "fresh cilantro"], { displayName: "Cilantro", category: "produce" }],
  [["parsley", "fresh parsley", "flat-leaf parsley"], { displayName: "Parsley", category: "produce" }],
  [["basil", "fresh basil"], { displayName: "Basil", category: "produce" }],
  [["mint", "fresh mint"], { displayName: "Mint", category: "produce" }],
  [["rosemary", "fresh rosemary"], { displayName: "Rosemary", category: "produce" }],
  [["thyme", "fresh thyme"], { displayName: "Thyme", category: "produce" }],
  [["dill", "fresh dill"], { displayName: "Dill", category: "produce" }],
  [["brussels sprout", "brussels sprouts"], { displayName: "Brussels Sprouts", category: "produce" }],
  [["eggplant"], { displayName: "Eggplant", category: "produce" }],
  [["artichoke", "artichokes"], { displayName: "Artichoke", category: "produce" }],
  [["beet", "beets"], { displayName: "Beet", category: "produce" }],
  [["radish", "radishes"], { displayName: "Radish", category: "produce" }],
  [["turnip", "turnips"], { displayName: "Turnip", category: "produce" }],
  [["leek", "leeks"], { displayName: "Leek", category: "produce" }],
  [["bok choy"], { displayName: "Bok Choy", category: "produce" }],
  [["pear", "pears"], { displayName: "Pear", category: "produce" }],
  [["peach", "peaches"], { displayName: "Peach", category: "produce" }],
  [["mango", "mangoes", "mangos"], { displayName: "Mango", category: "produce" }],
  [["pineapple"], { displayName: "Pineapple", category: "produce" }],
  [["watermelon"], { displayName: "Watermelon", category: "produce" }],

  // ── Meat ───────────────────────────────────────────────
  [["chicken breast", "chicken breasts", "boneless skinless chicken breast"], { displayName: "Chicken Breast", category: "meat" }],
  [["chicken thigh", "chicken thighs", "boneless skinless chicken thigh", "boneless skinless chicken thighs"], { displayName: "Chicken Thigh", category: "meat" }],
  [["chicken wing", "chicken wings"], { displayName: "Chicken Wings", category: "meat" }],
  [["chicken drumstick", "chicken drumsticks", "chicken leg", "chicken legs"], { displayName: "Chicken Drumstick", category: "meat" }],
  [["whole chicken"], { displayName: "Whole Chicken", category: "meat" }],
  [["ground beef"], { displayName: "Ground Beef", category: "meat" }],
  [["ground turkey"], { displayName: "Ground Turkey", category: "meat" }],
  [["ground pork", "ground pork sausage"], { displayName: "Ground Pork", category: "meat" }],
  [["ground chicken"], { displayName: "Ground Chicken", category: "meat" }],
  [["steak", "beef steak"], { displayName: "Steak", category: "meat" }],
  [["ribeye", "ribeye steak", "rib eye"], { displayName: "Ribeye Steak", category: "meat" }],
  [["sirloin", "sirloin steak"], { displayName: "Sirloin Steak", category: "meat" }],
  [["new york strip", "strip steak"], { displayName: "New York Strip", category: "meat" }],
  [["filet mignon", "beef tenderloin"], { displayName: "Beef Tenderloin", category: "meat" }],
  [["chuck roast", "beef chuck", "pot roast"], { displayName: "Chuck Roast", category: "meat" }],
  [["brisket", "beef brisket"], { displayName: "Brisket", category: "meat" }],
  [["flank steak"], { displayName: "Flank Steak", category: "meat" }],
  [["skirt steak"], { displayName: "Skirt Steak", category: "meat" }],
  [["stew meat", "beef stew meat"], { displayName: "Beef Stew Meat", category: "meat" }],
  [["pork chop", "pork chops", "bone-in pork chop"], { displayName: "Pork Chop", category: "meat" }],
  [["pork tenderloin"], { displayName: "Pork Tenderloin", category: "meat" }],
  [["pork shoulder", "pork butt", "boston butt"], { displayName: "Pork Shoulder", category: "meat" }],
  [["pork loin", "pork roast"], { displayName: "Pork Loin", category: "meat" }],
  [["bacon"], { displayName: "Bacon", category: "meat" }],
  [["ham"], { displayName: "Ham", category: "meat" }],
  [["sausage", "sausages", "pork sausage"], { displayName: "Sausage", category: "meat" }],
  [["italian sausage"], { displayName: "Italian Sausage", category: "meat" }],
  [["bratwurst", "brats"], { displayName: "Bratwurst", category: "meat" }],
  [["hot dog", "hot dogs", "frankfurter"], { displayName: "Hot Dogs", category: "meat" }],
  [["turkey breast"], { displayName: "Turkey Breast", category: "meat" }],
  [["lamb", "lamb chop", "lamb chops"], { displayName: "Lamb Chops", category: "meat" }],
  [["lamb leg", "leg of lamb"], { displayName: "Leg of Lamb", category: "meat" }],
  [["deli meat", "lunch meat", "deli turkey", "deli ham"], { displayName: "Deli Meat", category: "meat" }],
  [["pepperoni"], { displayName: "Pepperoni", category: "meat" }],
  [["salami"], { displayName: "Salami", category: "meat" }],
  [["prosciutto"], { displayName: "Prosciutto", category: "meat" }],

  // ── Seafood ────────────────────────────────────────────
  [["salmon", "salmon fillet", "salmon fillets"], { displayName: "Salmon", category: "seafood" }],
  [["shrimp", "raw shrimp", "shrimps"], { displayName: "Shrimp", category: "seafood" }],
  [["tuna", "tuna steak", "ahi tuna"], { displayName: "Tuna", category: "seafood" }],
  [["tilapia", "tilapia fillet", "tilapia fillets"], { displayName: "Tilapia", category: "seafood" }],
  [["cod", "cod fillet"], { displayName: "Cod", category: "seafood" }],
  [["halibut"], { displayName: "Halibut", category: "seafood" }],
  [["mahi mahi", "mahi-mahi"], { displayName: "Mahi Mahi", category: "seafood" }],
  [["sea bass"], { displayName: "Sea Bass", category: "seafood" }],
  [["catfish", "catfish fillet"], { displayName: "Catfish", category: "seafood" }],
  [["crab", "crab meat", "crabmeat"], { displayName: "Crab", category: "seafood" }],
  [["lobster", "lobster tail", "lobster tails"], { displayName: "Lobster", category: "seafood" }],
  [["scallop", "scallops", "sea scallops"], { displayName: "Scallops", category: "seafood" }],
  [["clam", "clams"], { displayName: "Clams", category: "seafood" }],
  [["mussel", "mussels"], { displayName: "Mussels", category: "seafood" }],
  [["oyster", "oysters"], { displayName: "Oysters", category: "seafood" }],
  [["squid", "calamari"], { displayName: "Calamari", category: "seafood" }],
  [["anchovy", "anchovies"], { displayName: "Anchovies", category: "seafood" }],

  // ── Dairy ──────────────────────────────────────────────
  [["milk", "whole milk"], { displayName: "Milk", category: "dairy" }],
  [["2% milk", "reduced fat milk"], { displayName: "2% Milk", category: "dairy" }],
  [["skim milk", "nonfat milk", "fat free milk"], { displayName: "Skim Milk", category: "dairy" }],
  [["half and half", "half & half"], { displayName: "Half & Half", category: "dairy" }],
  [["heavy cream", "heavy whipping cream", "whipping cream"], { displayName: "Heavy Cream", category: "dairy" }],
  [["butter", "unsalted butter"], { displayName: "Butter", category: "dairy" }],
  [["salted butter"], { displayName: "Salted Butter", category: "dairy" }],
  [["cream cheese"], { displayName: "Cream Cheese", category: "dairy" }],
  [["sour cream"], { displayName: "Sour Cream", category: "dairy" }],
  [["yogurt", "plain yogurt"], { displayName: "Yogurt", category: "dairy" }],
  [["greek yogurt"], { displayName: "Greek Yogurt", category: "dairy" }],
  [["cheddar", "cheddar cheese"], { displayName: "Cheddar Cheese", category: "dairy" }],
  [["sharp cheddar", "sharp cheddar cheese"], { displayName: "Sharp Cheddar", category: "dairy" }],
  [["mozzarella", "mozzarella cheese"], { displayName: "Mozzarella", category: "dairy" }],
  [["parmesan", "parmesan cheese", "parmigiano reggiano", "parmigiano-reggiano"], { displayName: "Parmesan", category: "dairy" }],
  [["swiss cheese", "swiss"], { displayName: "Swiss Cheese", category: "dairy" }],
  [["provolone", "provolone cheese"], { displayName: "Provolone", category: "dairy" }],
  [["gouda", "gouda cheese"], { displayName: "Gouda", category: "dairy" }],
  [["brie", "brie cheese"], { displayName: "Brie", category: "dairy" }],
  [["feta", "feta cheese"], { displayName: "Feta Cheese", category: "dairy" }],
  [["goat cheese", "chevre"], { displayName: "Goat Cheese", category: "dairy" }],
  [["ricotta", "ricotta cheese"], { displayName: "Ricotta", category: "dairy" }],
  [["cottage cheese"], { displayName: "Cottage Cheese", category: "dairy" }],
  [["american cheese", "american singles"], { displayName: "American Cheese", category: "dairy" }],
  [["pepper jack", "pepper jack cheese"], { displayName: "Pepper Jack", category: "dairy" }],
  [["colby jack", "colby-jack"], { displayName: "Colby Jack", category: "dairy" }],
  [["monterey jack"], { displayName: "Monterey Jack", category: "dairy" }],
  [["shredded cheese", "mexican blend", "mexican blend cheese"], { displayName: "Shredded Mexican Blend", category: "dairy" }],
  [["egg", "eggs", "large eggs"], { displayName: "Eggs", category: "dairy" }],
  [["whipped cream", "cool whip"], { displayName: "Whipped Cream", category: "dairy" }],

  // ── Bread ──────────────────────────────────────────────
  [["bread", "white bread", "sandwich bread"], { displayName: "Bread", category: "bread" }],
  [["whole wheat bread"], { displayName: "Whole Wheat Bread", category: "bread" }],
  [["sourdough", "sourdough bread"], { displayName: "Sourdough Bread", category: "bread" }],
  [["baguette", "french bread"], { displayName: "Baguette", category: "bread" }],
  [["tortilla", "tortillas", "flour tortilla", "flour tortillas"], { displayName: "Flour Tortillas", category: "bread" }],
  [["corn tortilla", "corn tortillas"], { displayName: "Corn Tortillas", category: "bread" }],
  [["pita", "pita bread"], { displayName: "Pita Bread", category: "bread" }],
  [["naan", "naan bread"], { displayName: "Naan", category: "bread" }],
  [["hamburger bun", "hamburger buns", "burger buns"], { displayName: "Hamburger Buns", category: "bread" }],
  [["hot dog bun", "hot dog buns"], { displayName: "Hot Dog Buns", category: "bread" }],
  [["english muffin", "english muffins"], { displayName: "English Muffins", category: "bread" }],
  [["bagel", "bagels"], { displayName: "Bagels", category: "bread" }],
  [["croissant", "croissants"], { displayName: "Croissants", category: "bread" }],
  [["breadcrumb", "breadcrumbs", "bread crumbs", "panko", "panko breadcrumbs"], { displayName: "Breadcrumbs", category: "bread" }],
  [["crouton", "croutons"], { displayName: "Croutons", category: "bread" }],

  // ── Pasta ──────────────────────────────────────────────
  [["spaghetti"], { displayName: "Spaghetti", category: "pasta" }],
  [["penne", "penne pasta"], { displayName: "Penne", category: "pasta" }],
  [["rigatoni"], { displayName: "Rigatoni", category: "pasta" }],
  [["fettuccine", "fettuccini"], { displayName: "Fettuccine", category: "pasta" }],
  [["linguine", "linguini"], { displayName: "Linguine", category: "pasta" }],
  [["angel hair", "angel hair pasta", "capellini"], { displayName: "Angel Hair", category: "pasta" }],
  [["macaroni", "elbow macaroni", "elbow pasta"], { displayName: "Macaroni", category: "pasta" }],
  [["farfalle", "bow tie pasta", "bowtie pasta"], { displayName: "Farfalle", category: "pasta" }],
  [["rotini"], { displayName: "Rotini", category: "pasta" }],
  [["orzo"], { displayName: "Orzo", category: "pasta" }],
  [["lasagna noodle", "lasagna noodles", "lasagna sheets"], { displayName: "Lasagna Noodles", category: "pasta" }],
  [["egg noodle", "egg noodles"], { displayName: "Egg Noodles", category: "pasta" }],
  [["ramen", "ramen noodles"], { displayName: "Ramen Noodles", category: "pasta" }],
  [["rice noodle", "rice noodles", "pad thai noodles"], { displayName: "Rice Noodles", category: "pasta" }],
  [["udon", "udon noodles"], { displayName: "Udon Noodles", category: "pasta" }],
  [["soba", "soba noodles"], { displayName: "Soba Noodles", category: "pasta" }],
  [["rice", "white rice", "long grain rice"], { displayName: "White Rice", category: "pasta" }],
  [["brown rice"], { displayName: "Brown Rice", category: "pasta" }],
  [["jasmine rice"], { displayName: "Jasmine Rice", category: "pasta" }],
  [["basmati rice", "basmati"], { displayName: "Basmati Rice", category: "pasta" }],
  [["quinoa"], { displayName: "Quinoa", category: "pasta" }],
  [["couscous"], { displayName: "Couscous", category: "pasta" }],

  // ── Canned ─────────────────────────────────────────────
  [["canned tomato", "canned tomatoes", "diced tomatoes"], { displayName: "Diced Tomatoes", category: "canned" }],
  [["crushed tomatoes"], { displayName: "Crushed Tomatoes", category: "canned" }],
  [["tomato sauce"], { displayName: "Tomato Sauce", category: "canned" }],
  [["tomato paste"], { displayName: "Tomato Paste", category: "canned" }],
  [["canned tuna", "tuna can"], { displayName: "Canned Tuna", category: "canned" }],
  [["canned chicken"], { displayName: "Canned Chicken", category: "canned" }],
  [["canned salmon"], { displayName: "Canned Salmon", category: "canned" }],
  [["black bean", "black beans", "canned black beans"], { displayName: "Black Beans", category: "canned" }],
  [["pinto bean", "pinto beans", "canned pinto beans"], { displayName: "Pinto Beans", category: "canned" }],
  [["kidney bean", "kidney beans", "canned kidney beans"], { displayName: "Kidney Beans", category: "canned" }],
  [["garbanzo bean", "garbanzo beans", "chickpea", "chickpeas", "canned chickpeas"], { displayName: "Chickpeas", category: "canned" }],
  [["refried beans", "canned refried beans"], { displayName: "Refried Beans", category: "canned" }],
  [["cannellini bean", "cannellini beans", "white beans", "great northern beans"], { displayName: "Cannellini Beans", category: "canned" }],
  [["lentil", "lentils"], { displayName: "Lentils", category: "canned" }],
  [["corn can", "canned corn"], { displayName: "Canned Corn", category: "canned" }],
  [["green chili", "green chilies", "diced green chilies"], { displayName: "Diced Green Chilies", category: "canned" }],
  [["rotel", "diced tomatoes and green chilies"], { displayName: "Rotel", category: "canned" }],
  [["coconut milk", "canned coconut milk"], { displayName: "Coconut Milk", category: "canned" }],
  [["broth", "chicken broth"], { displayName: "Chicken Broth", category: "canned" }],
  [["beef broth", "beef stock"], { displayName: "Beef Broth", category: "canned" }],
  [["vegetable broth", "vegetable stock"], { displayName: "Vegetable Broth", category: "canned" }],
  [["chicken stock"], { displayName: "Chicken Stock", category: "canned" }],
  [["enchilada sauce"], { displayName: "Enchilada Sauce", category: "canned" }],
  [["salsa verde"], { displayName: "Salsa Verde", category: "canned" }],

  // ── Condiments ─────────────────────────────────────────
  [["olive oil", "extra virgin olive oil", "evoo"], { displayName: "Olive Oil", category: "condiments" }],
  [["vegetable oil"], { displayName: "Vegetable Oil", category: "condiments" }],
  [["canola oil"], { displayName: "Canola Oil", category: "condiments" }],
  [["avocado oil"], { displayName: "Avocado Oil", category: "condiments" }],
  [["coconut oil"], { displayName: "Coconut Oil", category: "condiments" }],
  [["sesame oil"], { displayName: "Sesame Oil", category: "condiments" }],
  [["soy sauce", "soya sauce"], { displayName: "Soy Sauce", category: "condiments" }],
  [["fish sauce"], { displayName: "Fish Sauce", category: "condiments" }],
  [["worcestershire sauce", "worcestershire"], { displayName: "Worcestershire Sauce", category: "condiments" }],
  [["hot sauce", "tabasco", "franks hot sauce"], { displayName: "Hot Sauce", category: "condiments" }],
  [["sriracha"], { displayName: "Sriracha", category: "condiments" }],
  [["ketchup", "catsup"], { displayName: "Ketchup", category: "condiments" }],
  [["mustard", "yellow mustard"], { displayName: "Mustard", category: "condiments" }],
  [["dijon mustard", "dijon"], { displayName: "Dijon Mustard", category: "condiments" }],
  [["mayo", "mayonnaise"], { displayName: "Mayonnaise", category: "condiments" }],
  [["ranch", "ranch dressing"], { displayName: "Ranch Dressing", category: "condiments" }],
  [["bbq sauce", "barbecue sauce"], { displayName: "BBQ Sauce", category: "condiments" }],
  [["teriyaki sauce", "teriyaki"], { displayName: "Teriyaki Sauce", category: "condiments" }],
  [["hoisin sauce", "hoisin"], { displayName: "Hoisin Sauce", category: "condiments" }],
  [["oyster sauce"], { displayName: "Oyster Sauce", category: "condiments" }],
  [["vinegar", "white vinegar", "distilled vinegar"], { displayName: "White Vinegar", category: "condiments" }],
  [["apple cider vinegar"], { displayName: "Apple Cider Vinegar", category: "condiments" }],
  [["balsamic vinegar", "balsamic"], { displayName: "Balsamic Vinegar", category: "condiments" }],
  [["red wine vinegar"], { displayName: "Red Wine Vinegar", category: "condiments" }],
  [["rice vinegar", "rice wine vinegar"], { displayName: "Rice Vinegar", category: "condiments" }],
  [["salsa"], { displayName: "Salsa", category: "condiments" }],
  [["peanut butter"], { displayName: "Peanut Butter", category: "condiments" }],
  [["almond butter"], { displayName: "Almond Butter", category: "condiments" }],
  [["honey"], { displayName: "Honey", category: "condiments" }],
  [["maple syrup"], { displayName: "Maple Syrup", category: "condiments" }],
  [["jam", "jelly", "preserves"], { displayName: "Jam", category: "condiments" }],
  [["tahini"], { displayName: "Tahini", category: "condiments" }],
  [["miso", "miso paste"], { displayName: "Miso Paste", category: "condiments" }],
  [["curry paste", "red curry paste"], { displayName: "Red Curry Paste", category: "condiments" }],
  [["green curry paste"], { displayName: "Green Curry Paste", category: "condiments" }],
  [["sambal oelek", "chili garlic sauce"], { displayName: "Sambal Oelek", category: "condiments" }],
  [["gochujang"], { displayName: "Gochujang", category: "condiments" }],

  // ── Spices ─────────────────────────────────────────────
  [["salt", "table salt", "sea salt"], { displayName: "Salt", category: "spices" }],
  [["kosher salt"], { displayName: "Kosher Salt", category: "spices" }],
  [["black pepper", "pepper", "ground black pepper"], { displayName: "Black Pepper", category: "spices" }],
  [["garlic powder"], { displayName: "Garlic Powder", category: "spices" }],
  [["onion powder"], { displayName: "Onion Powder", category: "spices" }],
  [["paprika"], { displayName: "Paprika", category: "spices" }],
  [["smoked paprika"], { displayName: "Smoked Paprika", category: "spices" }],
  [["cayenne", "cayenne pepper"], { displayName: "Cayenne Pepper", category: "spices" }],
  [["chili powder"], { displayName: "Chili Powder", category: "spices" }],
  [["cumin", "ground cumin"], { displayName: "Cumin", category: "spices" }],
  [["coriander", "ground coriander"], { displayName: "Coriander", category: "spices" }],
  [["turmeric", "ground turmeric"], { displayName: "Turmeric", category: "spices" }],
  [["cinnamon", "ground cinnamon"], { displayName: "Cinnamon", category: "spices" }],
  [["nutmeg", "ground nutmeg"], { displayName: "Nutmeg", category: "spices" }],
  [["ginger powder", "ground ginger"], { displayName: "Ground Ginger", category: "spices" }],
  [["oregano", "dried oregano"], { displayName: "Oregano", category: "spices" }],
  [["basil dried", "dried basil"], { displayName: "Dried Basil", category: "spices" }],
  [["thyme dried", "dried thyme"], { displayName: "Dried Thyme", category: "spices" }],
  [["rosemary dried", "dried rosemary"], { displayName: "Dried Rosemary", category: "spices" }],
  [["bay leaf", "bay leaves"], { displayName: "Bay Leaves", category: "spices" }],
  [["italian seasoning"], { displayName: "Italian Seasoning", category: "spices" }],
  [["taco seasoning"], { displayName: "Taco Seasoning", category: "spices" }],
  [["red pepper flakes", "crushed red pepper", "red chili flakes"], { displayName: "Red Pepper Flakes", category: "spices" }],
  [["curry powder"], { displayName: "Curry Powder", category: "spices" }],
  [["garam masala"], { displayName: "Garam Masala", category: "spices" }],
  [["five spice", "chinese five spice", "five-spice"], { displayName: "Five Spice", category: "spices" }],
  [["old bay", "old bay seasoning"], { displayName: "Old Bay Seasoning", category: "spices" }],
  [["everything bagel seasoning"], { displayName: "Everything Bagel Seasoning", category: "spices" }],
  [["cardamom"], { displayName: "Cardamom", category: "spices" }],
  [["clove", "cloves", "ground cloves"], { displayName: "Cloves", category: "spices" }],
  [["allspice", "ground allspice"], { displayName: "Allspice", category: "spices" }],
  [["fennel seed", "fennel seeds"], { displayName: "Fennel Seeds", category: "spices" }],
  [["mustard seed", "mustard seeds"], { displayName: "Mustard Seeds", category: "spices" }],
  [["celery seed", "celery seeds"], { displayName: "Celery Seeds", category: "spices" }],
  [["sesame seed", "sesame seeds"], { displayName: "Sesame Seeds", category: "spices" }],
  [["poppy seed", "poppy seeds"], { displayName: "Poppy Seeds", category: "spices" }],
  [["vanilla", "vanilla extract"], { displayName: "Vanilla Extract", category: "spices" }],
  [["gochugaru", "korean red pepper flakes"], { displayName: "Gochugaru", category: "spices" }],
  [["za'atar", "zaatar"], { displayName: "Za'atar", category: "spices" }],
  [["sumac"], { displayName: "Sumac", category: "spices" }],
  [["saffron"], { displayName: "Saffron", category: "spices" }],
  [["msg", "monosodium glutamate"], { displayName: "MSG", category: "spices" }],

  // ── Pantry (dry goods / baking) ────────────────────────
  [["flour", "all-purpose flour", "all purpose flour", "ap flour"], { displayName: "All-Purpose Flour", category: "pantry" }],
  [["bread flour"], { displayName: "Bread Flour", category: "pantry" }],
  [["whole wheat flour"], { displayName: "Whole Wheat Flour", category: "pantry" }],
  [["almond flour"], { displayName: "Almond Flour", category: "pantry" }],
  [["cornstarch", "corn starch"], { displayName: "Cornstarch", category: "pantry" }],
  [["cornmeal", "corn meal"], { displayName: "Cornmeal", category: "pantry" }],
  [["sugar", "white sugar", "granulated sugar"], { displayName: "Sugar", category: "pantry" }],
  [["brown sugar", "light brown sugar"], { displayName: "Brown Sugar", category: "pantry" }],
  [["powdered sugar", "confectioners sugar", "icing sugar"], { displayName: "Powdered Sugar", category: "pantry" }],
  [["baking soda", "bicarbonate of soda"], { displayName: "Baking Soda", category: "pantry" }],
  [["baking powder"], { displayName: "Baking Powder", category: "pantry" }],
  [["yeast", "active dry yeast", "instant yeast"], { displayName: "Yeast", category: "pantry" }],
  [["chocolate chip", "chocolate chips", "semi-sweet chocolate chips"], { displayName: "Chocolate Chips", category: "pantry" }],
  [["cocoa powder", "unsweetened cocoa"], { displayName: "Cocoa Powder", category: "pantry" }],
  [["oat", "oats", "rolled oats", "old fashioned oats"], { displayName: "Rolled Oats", category: "pantry" }],
  [["cereal"], { displayName: "Cereal", category: "pantry" }],
  [["granola"], { displayName: "Granola", category: "pantry" }],
  [["nut", "nuts", "mixed nuts"], { displayName: "Mixed Nuts", category: "pantry" }],
  [["almond", "almonds"], { displayName: "Almonds", category: "pantry" }],
  [["walnut", "walnuts"], { displayName: "Walnuts", category: "pantry" }],
  [["pecan", "pecans"], { displayName: "Pecans", category: "pantry" }],
  [["cashew", "cashews"], { displayName: "Cashews", category: "pantry" }],
  [["pine nut", "pine nuts", "pignoli"], { displayName: "Pine Nuts", category: "pantry" }],
  [["peanut", "peanuts"], { displayName: "Peanuts", category: "pantry" }],
  [["raisin", "raisins"], { displayName: "Raisins", category: "pantry" }],
  [["dried cranberry", "dried cranberries", "craisins"], { displayName: "Dried Cranberries", category: "pantry" }],
  [["tortilla chip", "tortilla chips"], { displayName: "Tortilla Chips", category: "pantry" }],
  [["cracker", "crackers"], { displayName: "Crackers", category: "pantry" }],
  [["dried pasta", "pasta"], { displayName: "Pasta", category: "pasta" }],
  [["gelatin", "unflavored gelatin"], { displayName: "Gelatin", category: "pantry" }],

  // ── Frozen ─────────────────────────────────────────────
  [["frozen peas", "frozen pea"], { displayName: "Frozen Peas", category: "frozen" }],
  [["frozen corn", "frozen sweet corn"], { displayName: "Frozen Corn", category: "frozen" }],
  [["frozen broccoli"], { displayName: "Frozen Broccoli", category: "frozen" }],
  [["frozen spinach"], { displayName: "Frozen Spinach", category: "frozen" }],
  [["frozen mixed vegetables", "frozen vegetables", "frozen veggies"], { displayName: "Frozen Mixed Vegetables", category: "frozen" }],
  [["frozen berries", "frozen mixed berries"], { displayName: "Frozen Mixed Berries", category: "frozen" }],
  [["frozen strawberries"], { displayName: "Frozen Strawberries", category: "frozen" }],
  [["frozen shrimp"], { displayName: "Frozen Shrimp", category: "frozen" }],
  [["frozen pizza"], { displayName: "Frozen Pizza", category: "frozen" }],
  [["ice cream"], { displayName: "Ice Cream", category: "frozen" }],
  [["frozen fries", "french fries", "frozen french fries"], { displayName: "Frozen Fries", category: "frozen" }],
  [["frozen chicken nuggets", "chicken nuggets"], { displayName: "Chicken Nuggets", category: "frozen" }],
  [["frozen waffles", "waffles"], { displayName: "Frozen Waffles", category: "frozen" }],
  [["puff pastry"], { displayName: "Puff Pastry", category: "frozen" }],
  [["pie crust", "frozen pie crust"], { displayName: "Pie Crust", category: "frozen" }],
];

// Build the flat lookup map
export const CATEGORY_MAP = new Map<string, CategoryEntry>();

for (const [keys, entry] of entries) {
  const keyList = Array.isArray(keys) ? keys : [keys];
  for (const key of keyList) {
    CATEGORY_MAP.set(key.toLowerCase().trim(), entry);
  }
}
